services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
    - "8000:8000"
    environment:
    - DATABASE_URL=postgresql://user:password@db:5432/dbname
    depends_on:
    - db
    restart: always

  ui:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
    - "8501:8501"
    environment:
    - DATABASE_URL=postgresql://user:password@db:5432/dbname
    depends_on:
    - api
    restart: always

  db:
    image: postgres:13
    restart: always
    environment:
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=dbname
    volumes:
    - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: